### ISSUE TITLE
tts合成的播报语音文件，只识别出了部分文字，识别率较低。

### ISSUE THREAD

**Issue by cerberspace** [lovemefan/SenseVoice.cpp#12]
[新录音 92.zip](https://github.com/user-attachments/files/16942121/92.zip)
![2024-09-10 16-48-54 的屏幕截图](https://github.com/user-attachments/assets/04298edc-21b8-44c1-bbd2-c6b632214299)

**Comment by cerberspace** [comment]
是在Android手机端执行的结果。附上了wav文件和跑命令行的结果。

**Comment by lovemefan** [comment]
使用[sensevoice-python](https://github.com/lovemefan/SenseVoice-python)测试，一句话送入
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/3630d9bf-c682-4cdb-8088-4db61c8b8ea6">

vad切分送入
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/6b8d45f8-c368-4370-93d6-2118e4016cf0">

总结：长音频效果差，后续加入vad切分功能

**Comment by lovemefan** [comment]
已更新vad， 请更新代码，更新ggml，更新模型文件再次参数，感谢反馈
```
git pull
git submodule sync && git submodule update --init --recursive
```
