### ISSUE TITLE
CUDA推理结果有问题

### ISSUE THREAD

**Issue by Ivy233** [lovemefan/SenseVoice.cpp#13]
音频来源：iic/SenseVoiceSmall模型，examples/zh.mp3
用ffmpeg转成-ar 16000的wav。
CPU推理的结果：
![image](https://github.com/user-attachments/assets/0edffea9-f94e-43b7-9313-ea70b6fd6735)
GPU（4080Super）推理的结果：
![image](https://github.com/user-attachments/assets/83ec9311-ac74-449b-a8b5-dd24802ef44b)
nvidia-smi信息：
![image](https://github.com/user-attachments/assets/8538f215-a219-48ea-88e6-fda0515b0ce0)

**Comment by lovemefan** [comment]
CUDA适配包括Metal适配都卡在某一个算子上了，适配好了会在这个issue留言并发布release

**Comment by Ivy233** [comment]
问一手，现在有进展吗（）

**Comment by lovemefan** [comment]
> 问一手，现在有进展吗（）

最近忙了点😂，国庆尝试修复下

**Comment by Ivy233** [comment]
对照--no-gpu，目前已经确认到有三个地方有问题：
1. sense-voice-encoder.cpp那边encoder_layer_sanm_forward里，一开始的USE_CUDA对于norm的处理有问题，自己的代码已经修复这个问题。检测了几个值是完全一样的，先放一边了。
2. 第一层后续的QKV矩阵乘法中，对照发现会有0.001的误差，由于后续内容的存在，目前无法确认是否因为这个导致输出乱码，不过个人认为影响不是很大，除非后面的错误修复后还有乱码否则不考虑这个。
3. fsmn中的im2col基本确认是有问题的，似乎没有正确运行（具体原因还需要还在查）。

**Comment by lovemefan** [comment]
我是通过放开下面代码注释，打印tensor里面的值来对比的

https://github.com/lovemefan/SenseVoice.cpp/blob/0881ea5be2940f585a8426e2517d16480099d0c2/sense-voice/csrc/sense-voice-encoder.cc#L527

1. 由于第一层的norm的维度为560，560不是32的倍数，在ggml中会报错，后续通过pad均值到576（32的倍数），可正常计算。是否还有其他错误，如有欢迎指出或pr
2. 精度方面有一点损失，不是乱码主要原因。
3. 主要原因是im2col算子的问题，该问题在metal和cuda都存在。我在官方提了[issue](https://github.com/ggerganov/ggml/issues/931), 但是还没有回复，我个人排查起来非常困难。

**Comment by Ivy233** [comment]
第三点+1，简直有毒，要不手写？
第一点不是因为norm的32倍数问题，在扩展后，norm的560变成了576，对应的标准差也需要做缩放变换，表现在代码上是在计算最后加一个scale，倍率就是sqrt(576/560)。

**Comment by lovemefan** [comment]
norm没有注意到有个scale，感谢指出。im2col我看看再排查一下，先看看问问官方看看能不能修复，实在不行再想办法手写吧

**Comment by Ivy233** [comment]
第一点pr已经提了，注释内和没注释的都是可以跑的，都可以测一下。

**Comment by Ivy233** [comment]
今天是修好了吗，我刚才up看了一下直接好了

**Comment by Ivy233** [comment]
今天是修好了吗，我今天up之后发现看起来结果正常了。想问下是怎么解决的？

**Comment by lovemefan** [comment]
我把im2col算子单独放在cpu上计算，虽然相比全放在gpu上损失了部分速度，im2col能够跑通了。但是我自己测试在V100没跑通😂，cuda上的softmax出现nan了，所以没发release。

**Comment by lovemefan** [comment]
CUDA 12.0测试正常，最新 CUDA 12.6出现nan，等官方修复了

**Comment by Ivy233** [comment]
> 我把im2col算子单独放在cpu上计算，虽然相比全放在gpu上损失了部分速度，im2col能够跑通了。但是我自己测试在V100没跑通😂，cuda上的softmax出现nan了，所以没发release。

我后来跑了一下llama.cpp那边的ggml测试，同样规模的数据放在里面是OK的，数据又不太好搬过去，这下就很令人苦恼。
会不会是数据位数的问题，void*操作起来太危险了，还需要自己指定指针步进。之前debug的时候发现在cuda的global里面不按照正确的位数printf参数只会出现错位的情况，所以会有这个想法。

**Comment by Ivy233** [comment]
这东西自带的test-backend-ops似乎是能够编译的，我将其更新到最新的master后发现了一点不得了的东西。。。
我们的规模似乎输入进去似乎真的有问题，但是llama.cpp那边是OK的，会不会是有些bug修复没有同步过来。
下面是9.30最后一版，也是现在的SenseVoice.cpp采用的GGML，测试结果有问题：
![image](https://github.com/user-attachments/assets/b8b0a492-b182-48ba-af44-eb5b946edd6f)
这个是llama.cpp最新master的测试结果：
![image](https://github.com/user-attachments/assets/8886aabe-9243-4311-b3e6-77daeb8f1cb1
GGML BUG+1.jpg

**Comment by lovemefan** [comment]
👏👏👏，最近较忙，我周末也看看，顺便去官方反馈下

**Comment by lovemefan** [comment]
> ggml conv_1d 不支持 groups 参数，假设它的 conv_1d (groups = 1) 没有问题的话，是否可以参考 candle 的实现 https://github.com/huggingface/candle/blob/main/candle-core/src/conv.rs#L178 做成一个 for 循环

这个方式需要修改ggml中的算子了，目前方案是使用im2col算子加mul  间接实现了groups=channel的 conv_1d

**Comment by Ivy233** [comment]
应该已经修复了，GGML那边已经反馈并得到修复，不过似乎还没进master分支
https://github.com/ggerganov/ggml/issues/991

**Comment by lovemefan** [comment]
太好了！！！😀

**Comment by Ivy233** [comment]
我已经改了，希望merge一手，已经跑通了，顺便改了一下svg，那个有点旧了，重新跑了一个。

**Comment by lovemefan** [comment]
十分感谢！！！gpu终于算是跑通了

**Comment by Ivy233** [comment]
刚看了下，metal这边还有API变动，我这边没设备了，没辙

**Comment by lovemefan** [comment]
> 刚看了下，metal这边还有API变动，我这边没设备了，没辙

好嘞，我测试下
