### ISSUE TITLE
failed to read WAV file 'SenseVoice.cpp/data/test1.wav'

### ISSUE THREAD

**Issue by brisyramshere** [lovemefan/SenseVoice.cpp#14]
Expected subchunk1_id 0x20746d66. Given: 0x4b4e554a
error: failed to read WAV file 'SenseVoice.cpp/data/test1.wav'

我电脑上录了一个WAV格式音频，推理的时候提示以上错误，想问下是什么原因呢。

**Comment by lovemefan** [comment]
确保音频为 16kHz，单通道的wav，可以使用ffmpeg转换

```
ffmpeg -i /path/test1.wav -ar 16000 -ac 1 /path/output.wav
```

**Comment by brisyramshere** [comment]
> 确保音频为 16kHz，单通道的wav，可以使用ffmpeg转换
> 
> ```
> ffmpeg -i /path/test1.wav -ar 16000 -ac 1 /path/output.wav
> ```

了解了，谢谢
