### ISSUE TITLE
翻译效率问题

### ISSUE THREAD

**Issue by yjloong** [lovemefan/SenseVoice.cpp#19]
请问为什么我使用python版本SenseVoiceSmall，翻译音频时间，都几乎比cpp要快十几倍。相同的CPU线程数4，内存不限量情况下，python版本占内存能达到16G，cpp只用2.2G，模型使用的ggml f32.

**Comment by yjloong** [comment]
我看大部分时间都是在encoder哪里。几乎占了95%的时间。

**Comment by lovemefan** [comment]
使用的是否是长音频，目前cpp端处理长音频会很慢，需要像python版用vad切分在转译

**Comment by yjloong** [comment]
我这边是2s音频测试也差不多这样。

**Comment by lovemefan** [comment]
能否贴一下日志

**Comment by yjloong** [comment]
![image](https://github.com/user-attachments/assets/7fa7f6a5-ed7c-41c6-8484-11885faa7218)

**Comment by yjloong** [comment]
抱歉，之前没有在这个环境。

**Comment by yjloong** [comment]
![image](https://github.com/user-attachments/assets/6cbeffa0-fcfb-4538-bbcf-3cf347e8e079)
![image](https://github.com/user-attachments/assets/c59bbc3c-3c7d-4404-b9da-9a8d53f57640)

**Comment by lovemefan** [comment]
确保编译的时候CMAKE_BUILD_TYPE=Release，开启03优化,。  4线程 rtf 0.89不太正常，应该在0.2左右， ggml虽然没有onnx快，但是不会相差这么多
```bash
cmake -DCMAKE_BUILD_TYPE=Release ..
```

**Comment by lovemefan** [comment]
已更新vad，支持长音频， 请更新代码，更新ggml，更新模型文件再次尝试
```
git pull
git submodule sync && git submodule update --init --recursive
```
