### ISSUE TITLE
日志输出和示例上的不一致,  没有输出识别结果呢

### ISSUE THREAD

**Issue by kingyang** [lovemefan/SenseVoice.cpp#2]
./sense-voice-main.exe -m "./gguf-fp32-sense-voice-small.bin" "./无间道-天台~1.wav" -t 4
sense_voice_small_init_from_file_with_params_no_state: loading model from 'D:\github\SenseVoiceGGUF\gguf-fp32-sense-voice-small.bin'
sense_voice_init_with_params_no_state: use gpu    = 1
sense_voice_init_with_params_no_state: flash attn = 0
sense_voice_init_with_params_no_state: gpu_device = 0
sense_voice_model_load: version:      3
sense_voice_model_load: alignment:   32
sense_voice_model_load: data offset: 444480
sense_voice_model_load: loading model
sense_voice_model_load: n_vocab = 25055
sense_voice_model_load: n_encoder_hidden_state = 512
sense_voice_model_load: n_encoder_linear_units = 2048
sense_voice_model_load: n_encoder_attention_heads  = 4
sense_voice_model_load: n_encoder_layers = 50
sense_voice_model_load: n_mels  = 80
sense_voice_model_load: ftype  = 1
sense_voice_model_load: vocab[25055] loaded
sense_voice_model_load: CPU total size =   935.21 MB
sense_voice_model_load: n_tensors: 1197
sense_voice_model_load: load SenseVoiceSmall takes 0.701000 second
sense_voice_init_state: kv pad  size  =    3.67 MB
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: reallocating buffers automatically
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 59.34 MiB
sense_voice_init_state: compute buffer (encoder)   =   65.31 MB
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: reallocating buffers automatically
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 10.14 MiB
sense_voice_init_state: compute buffer (decoder)   =   13.72 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0

main: processing audio (4842419 samples, 219.61084 sec) , 4 threads, 1 processors, lang = auto...

控制台输出这些就完了,  我看进程退出code是3
[无间道-天台~1.zip](https://github.com/user-attachments/files/16639481/-.1.zip)

**Comment by kingyang** [comment]
看代码 是`error: failed to initialize sense voice context` ,

我是window 11系统

**Comment by lovemefan** [comment]
感谢回馈，目前模型没有加入vad切分，两百多秒长音频应该会直接爆内存，如果短音频同样出现该问题那确实存在bug。当前还没有在其他系统测试充分，如果还有其他问题请继续留言，我后续将持续跟进。

**Comment by kingyang** [comment]
嗯 在windows中换短音频 可以正常输出
不过同样的音频在wsl中可以可以输出的

**Comment by cerberspace** [comment]
sense_voice_small_init_from_file_with_params_no_state: loading model from '/sdcard/gguf-fp16-sense-voice-small.bin'
sense_voice_init_with_params_no_state: use gpu    = 0
sense_voice_init_with_params_no_state: flash attn = 0
sense_voice_init_with_params_no_state: gpu_device = 0
sense_voice_model_load: version:      3
sense_voice_model_load: alignment:   32
sense_voice_model_load: data offset: 444480
sense_voice_model_load: loading model
sense_voice_model_load: n_vocab = 25055
sense_voice_model_load: n_encoder_hidden_state = 512
sense_voice_model_load: n_encoder_linear_units = 2048
sense_voice_model_load: n_encoder_attention_heads  = 4
sense_voice_model_load: n_encoder_layers = 50
sense_voice_model_load: n_mels  = 80
sense_voice_model_load: ftype  = 1
sense_voice_model_load: vocab[25055] loaded
sense_voice_model_load: CPU total size =   468.98 MB
sense_voice_model_load: n_tensors: 1197
sense_voice_model_load: load SenseVoiceSmall takes 0.730000 second 
sense_voice_init_state: kv pad  size  =    3.67 MB
sense_voice_init_state: compute buffer (encoder)   =   65.31 MB
sense_voice_init_state: compute buffer (decoder)   =   13.72 MB

system_info: n_threads = 4 / 8 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | METAL = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0

main: processing audio (649509 samples, 40.59431 sec) , 4 threads, 1 processors, lang = auto...

sense_voice_pcm_to_feature_with_state: calculate fbank and cmvn takes 65.858 ms
<|en|><|EMO_UNKNOWN|><|BGM|><|withitn|>The.
sense_voice_full_with_state: decoder audio use 16.250042 s, rtf is 0.400303. 
我是在手机端跑，识别的内容不稳定，有时输出正确，有时输出如上；编译时加和不加-O3优化选项耗时相差10倍

**Comment by lovemefan** [comment]
感谢反馈，能否将sense-voice-encoder.cc:480 注释打开（日志较多），提供一下音频和日志，感谢
https://github.com/lovemefan/SenseVoice.cpp/blob/ca4bc0f73bbd39b7447b9b5af851eca427171ab9/sense-voice/csrc/sense-voice-encoder.cc#L480

**Comment by cerberspace** [comment]
[wav&log.zip](https://github.com/user-attachments/files/16687957/wav.log.zip)
已上传wav文件和手机log

**Comment by cerberspace** [comment]
ggml_backend_sched_set_eval_callback 放开这个，手机的log中似乎也没有打印ggml相关的log

**Comment by lovemefan** [comment]
> ggml_backend_sched_set_eval_callback 放开这个，手机的log中似乎也没有打印ggml相关的log

感谢反馈，已复现该bug

**Comment by lovemefan** [comment]
> [wav&log.zip](https://github.com/user-attachments/files/16687957/wav.log.zip) 已上传wav文件和手机log

当前bug已排查到了， double数组在arm cpu的初始化过程中有一定几率会初始化NaN， 解决办法就是手动初始化为0。更新一下最新代码就好了。
麻烦帮忙再测试下识别内容是否正确。

https://github.com/lovemefan/SenseVoice.cpp/blob/7e8daa3afc7094cd0c81d1b1f3b55658a69e83f7/sense-voice/csrc/sense-voice-frontend.cc#L77-L82

**Comment by cerberspace** [comment]
> > [wav&log.zip](https://github.com/user-attachments/files/16687957/wav.log.zip) 已上传wav文件和手机log
> 
> 当前bug已排查到了， double数组在arm cpu的初始化过程中有一定几率会初始化NaN， 解决办法就是手动初始化为0。更新一下最新代码就好了。 麻烦帮忙再测试下识别内容是否正确。
> 
> https://github.com/lovemefan/SenseVoice.cpp/blob/7e8daa3afc7094cd0c81d1b1f3b55658a69e83f7/sense-voice/csrc/sense-voice-frontend.cc#L77-L82

已验证，正常了。我有另一个问题想要咨询，我新开一个issues。
