### ISSUE TITLE
sensevoice.cpp是不支持pcm语音的输入识别吗？

### ISSUE THREAD

**Issue by Nicksooooo** [lovemefan/SenseVoice.cpp#20]
无法识别pcm格式的语音输入

**Comment by lovemefan** [comment]
计算fbank时实际上是pcm数据，wav格式的文件仅比pcm流多了头部，可以直接跳过读取wav文件将pcm数据送入计算特征

**Comment by soulmayon** [comment]
似乎有的wav文件不能读取，播放和用whisper都没问题，附上一个样本，由于附件不能传wav文件，我改成jpg后缀，看看能不能收到。
![1](https://github.com/user-attachments/assets/6097a1d7-6770-47de-b765-0aa4283cfb09)

**Comment by soulmayon** [comment]
另存为wav即可，这个文件就不能读取

**Comment by lovemefan** [comment]
目前wav只支持采样率为16000 Hz，单通道音频

**Comment by lovemefan** [comment]
已支持vad模型，支持改造成伪流式模型
