### ISSUE TITLE
MacBook Pro M1 按照说明编译报错

### ISSUE THREAD

**Issue by soulmayon** [lovemefan/SenseVoice.cpp#25]
`/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice-decoder.cc:125:13: error: use of undeclared identifier 'ggml_backend_metal_set_n_cb'
            ggml_backend_metal_set_n_cb(backend, n_threads);
            ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:120:25: warning: unused variable 'key' [-Wunused-variable]
            const char *key = gguf_get_key(gguf_ctx, i);
                        ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:175:22: warning: unused variable 'scale' [-Wunused-variable]
        const size_t scale = sense_voice.hparams.ftype ? 1 : 2;
                     ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:262:20: warning: variable 'buffer_size' set but not used [-Wunused-but-set-variable]
            size_t buffer_size = 32*1024; // need some extra room??
                   ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:237:21: warning: unused variable 'hparams' [-Wunused-variable]
        const auto &hparams = sense_voice.hparams;
                    ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:229:12: warning: unused variable 'ctx_size' [-Wunused-variable]
    size_t ctx_size = 0;
           ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:231:21: warning: unused variable 'wtype' [-Wunused-variable]
    const ggml_type wtype = sctx.wtype;
                    ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:232:21: warning: unused variable 'vtype' [-Wunused-variable]
    const ggml_type vtype =
                    ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice-encoder.cc:113:9: error: use of undeclared identifier 'ggml_backend_metal_log_set_callback'
        ggml_backend_metal_log_set_callback(g_state.log_callback,
        ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/examples/common-ggml.cc:250:17: warning: variable 'nelements' set but not used [-Wunused-but-set-variable]
        int32_t nelements = 1;
                ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/examples/common-ggml.cc:336:21: warning: variable 'f32_data' is uninitialized when used here [-Wuninitialized]/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice-encoder.cc:
163:13: error:                     f32_data[i] = ggml_fp16_to_fp32(data_f16[i]);
use of undeclared identifier 'ggml_backend_metal_set_n_cb'                    ^~~~~~~~

            ggml_backend_metal_set_n_cb(backend, n_threads);
            ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/examples/common-ggml.cc:329:29: note: initialize the variable 'f32_data' to silence this warning
            float * f32_data;
                            ^
                             = nullptr
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice-encoder.cc:458:17: warning: unused variable 'model' [-Wunused-variable]
    const auto &model = ctx.model;
                ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:410:9: error: use of undeclared identifier 'ggml_backend_metal_log_set_callback'
        ggml_backend_metal_log_set_callback(g_state.log_callback, g_state.log_callback_user_data);
        ^
/Users/soulmayon/desktop/ali/SenseVoice.cpp/sense-voice/csrc/sense-voice.cc:763:19: warning: unused variable 'n_ctx' [-Wunused-variable]
        const int n_ctx = state->feature.n_len;
                  ^
`

**Comment by lovemefan** [comment]
由于最新ggml的api变化，请更新最新代码

**Comment by soulmayon** [comment]
已更新，这次只有警告warning: unused variable但不报错了，非常感谢
