### ISSUE TITLE
长音频识别效果较差

### ISSUE THREAD

**Issue by Ivy233** [lovemefan/SenseVoice.cpp#26]
个人这边检测发现：
1. 最终state.ids长度只有1000左右时，基本都能识别到，输出也基本可读。
2. 最终state.ids长度有8000左右时（对应的音频有8min），会出现大段大段的id=0的情况，一下子能跳好几百个token。
想问下这种问题是否遇到过，有没有排查过值的原因？

**Comment by lovemefan** [comment]
有遇到过，这个是模型问题，#12 中有例子，此非流式模型适合先用vad切分成小段，然后再识别。vad模型得争取抽时间加一下才更加实用

**Comment by lovemefan** [comment]
已更新vad，可以重新测试啦
