### ISSUE TITLE
windows运行提示到cocab[25055] loaded 后没有其他输出，是奔溃了吗

### ISSUE THREAD

**Issue by chenghuiwen** [lovemefan/SenseVoice.cpp#31]
![屏幕截图 2024-11-28 163051](https://github.com/user-attachments/assets/a4954f2d-43ce-41ac-a704-32355d5b711a)

**Comment by lovemefan** [comment]
请更新最新代码，更新ggml, 更新最新的模型文件， 参数加上-ng 再次尝试
```
git pull
git submodule sync && git submodule update --init --recursive
```

**Comment by chenghuiwen** [comment]
更新了sensevoice和ggml代码，我看你这边huggingface模型没有更新，我就没有更新了，比之前多走了几步，但是还是没有输出，可以帮忙看下哪儿没配好吗

**Comment by chenghuiwen** [comment]
走到了sense_voice_init_state: kv pad size = 3.64M

**Comment by lovemefan** [comment]
modelscope 已上传， huggingface还没更新

**Comment by chenghuiwen** [comment]
可以跑起来了，但是识别结果是乱码。需要更新词表吗？

**Comment by chenghuiwen** [comment]
有部分异常提示 ggml_gallocr_needs_realloc: node node_0 is not valid

**Comment by lovemefan** [comment]
部分异常不影响识别，能否提供音频我试试能不能复现乱码

**Comment by chenghuiwen** [comment]
目前用的是huggingface上的那一段音频

**Comment by chenghuiwen** [comment]
调试出来了，是因为VS 工作台输出中文需要设置一下。SetConsoleOutput(CP_UTF8)

**Comment by chenghuiwen** [comment]
但是在windows上，sense_voice_free 清除变量奔溃
