### ISSUE TITLE
`--help` 等命令不应该输出到 stderr 吧

### ISSUE THREAD

**Issue by lalala-233** [lovemefan/SenseVoice.cpp#32]
很多软件（如 gcc、git）默认都是输出到 stdout，输出到 stderr 通常应该是错误信息吧……

https://github.com/lovemefan/SenseVoice.cpp/blob/9b7cb22443e123adb26048e72b877c0139d5a74a/sense-voice/csrc/main.cc#L114-L118

**Comment by lovemefan** [comment]
这些属于调试信息中的错误提示信息， 输出的信息会立刻被写到屏幕或日志文件中，而语音识别结果会输出到 stdout。

这种分离可以使得用户可以更容易地利用重定向将语音识别结果输出到文件中, 不会参杂其他的中间信息。例如：

```bash
/sense-voice-main -m  /path/to/sense-voice-small-fp16.gguf /path/to/audio.wav -t 8  -ng  > transcript.txt

```

stderr 输出程序的错误提示、警告和调试信息， stdout 输出程序结果，即语音识别结果
