### ISSUE TITLE
识别不出数字

### ISSUE THREAD

**Issue by TechManDexiang** [lovemefan/SenseVoice.cpp#33]
我在语音中说出1 2 3 4 5 6 7 8 9，只要是含有数字的，都识别不出来，这是咋回事呢

**Comment by lovemefan** [comment]
请问题解决了吗， 最近忙，还没来及回复

**Comment by TechManDexiang** [comment]
问题解决了，这应该是我自己的问题，我是改了一下代码，生成了.so库，后来换成.a库就好了

**Comment by lovemefan** [comment]
新版更新了vad模型，支持长音频了
