### ISSUE TITLE
Can it support Q4 or Q8 quantization?

### ISSUE THREAD

**Issue by edisonzf2020** [lovemefan/SenseVoice.cpp#4]

**Comment by lovemefan** [comment]
Yes, thanks to the whisper.cpp, more quantized models will be supported in the future, and I’m also looking forward to the  release of SenseVoice-Large

**Comment by edisonzf2020** [comment]
cool
And can support mp3 input?

**Comment by lovemefan** [comment]
> cool And can support mp3 input first?

Use ffmpeg convert mp3 to wav
```bash
ffmpeg -i /path/xxx.mp3 -ar 16000 -ac 1 /path/output.wav
```

**Comment by lovemefan** [comment]
Support Q3, Q4, Q5, Q6, Q8 quantization now.
