### ISSUE TITLE
实现时间戳功能

### ISSUE THREAD

**Issue by cerberspace** [lovemefan/SenseVoice.cpp#5]
目前一个初步的想法是根据目前分块的每块大小960个samples  按照目前处理的16k的采样率的数据，每块是60ms，最后CTC输出的有序的ids中对应的token的时长就是它所在顺序*60ms，是否是这样理解呢，代码层面我就直接这么写了：
            //对于前处理时每个token的时间以960 samples 60ms 每一块，以此为估算出每个token的所在的位置的时间戳
sense-voice-decoder.cc文件：128行
```
            int i=0, step=60;
            for(int id: state.ids){
                if (id != 0) {
                    SENSE_VOICE_LOG_INFO("%s: %s", to_timestamp(step*(i>3? i-4:i), false).c_str(), ctx.vocab.id_to_token[id].c_str());
                }
                i++;
            }
            SENSEVOICE_LOG_INFO("size is %d", state.ids.size());
```

**Comment by lovemefan** [comment]
可以这样理解， 1秒的音频为16000帧数据，经过特征提取fbank变成了97帧，再进过lfr变成了15帧，最后ctc输出为对应的15个logit，也就是60ms/per ，直接按照每60ms每个token其实是可以的，前提是切分的粒度和准确度可以接受。
据我了解，目前较为成熟的对齐算法有两个，分别是dwt(whisper.cpp在使用)和ctc-alignment（torchaudio、wenet在使用），这两个算法输入是ctc出来的概率矩阵，时间戳会更精确。

**Comment by cerberspace** [comment]
如果不是计算到token-level的时间戳，仅仅是segment断句，只纪录断句start-end时间戳呢？

**Comment by lovemefan** [comment]
应该可以的，可以验证一下，可以先这样用着，后续我会慢慢地加vad和时间戳功能的

**Comment by cerberspace** [comment]
thanks，每一个点展开都是一篇文章了，我也边写边学，有机会也贡献一点上来。

**Comment by lovemefan** [comment]
> thanks，每一个点展开都是一篇文章了，我也边写边学，有机会也贡献一点上来。

我也是边学边写的，还有很多东西不会😂，共同进步，欢迎贡献

**Comment by lovemefan** [comment]
配合vad已实现句子级别的时间戳

**Comment by XWHQSJ** [comment]
正在尝试实现单词级时间戳
