### ISSUE TITLE
ggml框架在大多数情况下会比onnx快吗？有onnx兼容性强吗？

### ISSUE THREAD

**Issue by yuyun2000** [lovemefan/SenseVoice.cpp#7]
师兄带带

**Comment by lovemefan** [comment]
SenseVoice.cpp 在cpu上速度相对onnx没有太大优势，但是可以尽量保证语音识别的实时性，速度方面需要大量优化工作，但是ggml支持很多后端，例如metal、cuda、vulkan、还有amd、inter的GPU，这些都需要花时间适配

**Comment by yuyun2000** [comment]
好吧，看来低端设备上还是onnx兼容强一点啊

**Comment by coreeey** [comment]
请问ggml内存占用和onnx比差距大吗？

**Comment by lovemefan** [comment]
> 请问ggml内存占用和onnx比差距大吗？

ggml在q4量化下内存占用小于300m

<img width="1214" height="98" alt="Image" src="https://github.com/user-attachments/assets/94fd4fd4-9fc6-4f49-a22f-3bae815a63d4" />
